---
- name: Subir imagen nginx al ACR
  hosts: vm
  remote_user: adminUsername
  gather_facts: no
  vars_files:
    - vars/vars_global.yaml

  tasks:
    - name: Pull de imagen de nginx
      containers.podman.podman_image:
        name: docker.io/nginx

    - name: Tag de la imagen a casopractico2
      containers.podman.podman_tag:
        image: docker.io/nginx:latest
        target_names:
          - nginx:casopractico2

    - name: Push de la imagen tagueada casopractico2 al ACR
      containers.podman.podman_image:
        name: nginx:casopractico2
        push: true
        username: "{{ acr_username }}"
        password: "{{ acr_password }}"
        push_args:
          dest:  "{{ acr_server }}"